generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Order
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          order
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ id, processed, email, orderhash, payerstatus, firstname, lastname, addressstatus, shiptocountrycode, quantity, shipping, total, status ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
