<?php

/**
 * DonationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonationTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object DonationTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Donation');
  }

  public static function findById($id) {
    return self::getInstance()->find($id);
  }

  public static function getSuccessfulDonationsQuery($limit) {
    // build the query
    $q = Doctrine_Query::create()
    ->from('Donation d')
    ->where('d.status = "Successful"')
    ->orderBy("d.created_at DESC");
    if($limit!="") {
      $q->limit($limit);
    }
    // return the query
    return $q;
  }
  
  public static function getSuccessfulDonations($limit="") { 
    // if we dont have a limit passed in as a param, set limit to 5
 
    $q = self::getSuccessfulDonationsQuery($limit);
     
    $donations = $q->execute();
    return $donations;
  }
  
  public static function findByHash($donationhash) {
    return self::getInstance()->findBy("donationhash", $donationhash);
  }
    
  /**
   * calculate the total number of successful donations 
   */
  public static function getAllTotalDonations() {
    $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
    $query = "SELECT SUM(total) FROM donations WHERE status = :status";
    $stmt = $pdo->prepare($query);

    $params = array(
      "status"  => "Successful"
    );
    $stmt->execute($params);
    $results = $stmt->fetchAll();
    
    return $results;
    
  }
}