# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

live:
  .settings:
    no_script_name:         true
    logging_enabled:        false

stage:
  .settings:
    no_script_name:         true
    logging_enabled:        false
dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  true
    no_script_name:         true
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            6b1c33ce7e076d9f816577ac39d72eaee9fd5907

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    no_script_name:         true
    # Enable the database manager
    use_database:           true
